mint:
  owner_address: 'kQBR94p4TAivOi9mpGIoi-U2OH_TwuP01GfBtXf9QLMt_6vm'
  coll_ng: 70_000_000   # 0.07 TON
  item_ng: 50_000_000   # 0.05 TON
  list:
    - item_index: 0
      item_content_uri: 'QmWBXB7PghQpG1sD2mQjiKBDjhTmTG7CBuEdXWnW7TPeRW?filename=harold3.jpg'
    - item_index: 1
      item_content_uri: 'QmfKawqCp7zxa5uckmmU7kshCLDduiciCp4N6WCeZcd9Pw?filename=math3.jpeg'
    - item_index: 2
      item_content_uri: 'QmP7YPwQK1RfrQwxMawY8Ez4HdTDznKoJY1hhvvNg7bEfe?filename=googe_dino3.png'
